name: demo vars
on: # [workflow_dispatch, push, fork]
    workflow_dispatch:
env:
    CONTENT: "sono il contenuto della variabile"
jobs:
    print:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        name: print
        environment: DEVELOPMENT
        runs-on: ${{ matrix.os }}
        env:
            TITLE: "sono il titolo"
        steps:
            - name: print title
              continue-on-error: false
              run: | 
                exit
                echo titolo: ${{ env.TITLE }}
                echo contenuto: ${{ env.CONTENT }}
            - name: print api key
              run: echo api_key -> ${{ vars.API_KEY }}
    print-no-env:
        needs: print
        if: always()
        name: print-no-env
        runs-on: ubuntu-latest
        steps:
            - name: print
              run: echo api_key -> ${{ vars.API_KEY }}