name: demo vars
on: # [workflow_dispatch, push, fork]
    workflow_dispatch:
        inputs:
            TITLE:
                description: title
                required: true
                type: string
env:
    CONTENT: "sono il contenuto della variabile"
jobs:
    print:
        # strategy:
        #     matrix:
        #         os: [ubuntu-latest, windows-latest, macos-latest]
        name: print
        environment: DEVELOPMENT
        runs-on: ubuntu-latest
        env:
            TITLE: "sono il titolo"
        steps:
            - name: print title
              continue-on-error: false
              run: | 
                ghrehhrhernhfh
                echo titolo: ${{ env.TITLE }}
                echo contenuto: ${{ env.CONTENT }}
            - name: print api key
              run: echo api_key -> ${{ vars.API_KEY }}
    print-no-env:
        needs: print
        if: success()
        name: print-no-env
        runs-on: ubuntu-latest
        steps:
            - name: print
              run: echo api_key -> ${{ vars.API_KEY }}