name: demo vars
on:
    workflow_dispatch:
env:
    CONTENT: "sono il contenuto della variabile"
jobs:
    print:
        name: print
        environment: DEVELOPMENT
        runs-on: ubuntu-latest
        env:
            TITLE: "sono il titolo"
        steps:
            - name: print title
              run: | 
                echo titolo: ${{ env.TITLE }}
                echo contenuto: ${{ env.CONTENT }}
            - name: print api key
              run: echo api_key -> ${{ secrets.API_KEY }}